language: ruby
cache: bundler

rvm:
  - jruby
  - 2.0.0
  - 2.1.2

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - amar4enko@gmail.com
    on_failure: change
    on_success: never